//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_mixedreality : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 LeftPadTracker
        {
            get
            {
                return SteamVR_Actions.mixedreality_LeftPadTracker;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightPadTracker
        {
            get
            {
                return SteamVR_Actions.mixedreality_RightPadTracker;
            }
        }
        
        public virtual SteamVR_Action_Boolean PressTrigger
        {
            get
            {
                return SteamVR_Actions.mixedreality_PressTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean PressMenu
        {
            get
            {
                return SteamVR_Actions.mixedreality_PressMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftPadTrackerPressed
        {
            get
            {
                return SteamVR_Actions.mixedreality_LeftPadTrackerPressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightPadTrackerPressed
        {
            get
            {
                return SteamVR_Actions.mixedreality_RightPadTrackerPressed;
            }
        }
    }
}
